#!/usr/bin/php -q
<?php
/**
 * @todo Enable script to create .htaccess files instead of having the user set up the server config with <Location>
 */
include 'helpers/directory.php';

define('PHRAILS_VERSION', '0.01');
define('CUR_DIR', dirname(__FILE__));

$script_name = array_shift($argv);
$path = array_shift($argv);
$include_framework = array_shift($argv);
if($include_framework === null)
	$include_framework = 'false';
$htaccess = array_shift($argv);
$doht = false;
if($htaccess === 'true')
	$doht = true;



if($path !== null){
	//Create the structure.
	create_structure($path);
	
	//Do we need to clone the framework into the directory?
	if($include_framework === 'true'){
		print "\n" . 'Cloning Phrails from github.com.' . "\n";
		exec("git clone git@github.com:mediaslave/phrails.git $path/framework");
		print 'Phrails was cloned.' . "\n";
	}
}
else{
	print 'Must specify a name for the project. Example: ./phrails /home/jpalmer/to-do.';
}
/**
 * Create the directory structure for a project.
 *
 * @param string $path 
 * @return void
 * @author Justin Palmer
 */
function create_structure($path){
	create_directory($path);
		create_file('index.php', $path);
		//app
		create_directory($path . '/app');
		create_directory($path . '/app/controllers');
			create_file('ApplicationController.php', $path . '/app/controllers');
		create_directory($path . '/app/helpers');
		create_directory($path . '/app/models');
		create_directory($path . '/app/views');
		create_directory($path . '/app/views/layouts');
			create_file('application.html.php', $path . '/app/views/layouts');
		//config
		create_directory($path . '/config');
			create_file('database.ini', $path . '/config');
			create_file('environment.php', $path . '/config');
			create_file('routes.php', $path . '/config');
		create_directory($path . '/config/environments');	
			create_file('development.php', $path . '/config/environments');
			create_file('production.php', $path . '/config/environments');
		//lib
		create_directory($path . '/lib');
		//public
		create_directory($path . '/public');
		create_directory($path . '/public/images');
		create_directory($path . '/public/javascript');
		create_directory($path . '/public/stylesheets');
		//script
		create_directory($path . '/script');
			create_file('generate', $path . '/script');
			exec("chmod +x $path/script/generate");
		create_directory($path . '/script/rake');
			create_file('routes', $path . '/script/rake');
			create_file('rake', $path);
			exec("chmod +x $path/rake");
		//temp
		create_directory($path . '/tmp');
		create_directory($path . '/tmp/cache');
			exec("chmod 777 $path/tmp/cache");
		//vendor
		create_directory($path . '/vendor');
		create_directory($path . '/vendor/plugins');
}