#!/usr/bin/php -q
<?php
include 'boot.php';
define('PROJECT_ROOT', '');
$script = array_shift($argv);
$operation = array_shift($argv);
$name = array_shift($argv);

switch(strtolower($operation)){
	case 'controller':
		generate_controller($name, $argv);
		break;
	case 'model':
		generate_model($name);
		break;
	case 'migration':
		generate_migration($name, false);
		break;
	default:
		print 'Unknown generator: ' . $operation . "\n\nThe known generators are 'controller', 'model' and 'migration'";
}

function generate_model($name){
	$namespace = PR_APPLICATION_NAMESPACE;
	$model = <<<MODEL
<?php
/**
 * Namespace for models
 */
namespace $namespace\app\model;
/**
 * PageBlock
 */
/**
 * ClassBlock
 */
class $name extends Model{
	
	
	/**
	 * Add rules for this model.
	 *
	 * @author
	 */
	public function init(){
		
	}
}
MODEL;
	write_file($model, PROJECT_ROOT . 'app/models/' . $name . ".php");
	generate_migration($name);
}


function generate_migration($name, $create=true)
{
	if($create)
		$name = 'create_' . $name;
		$name = date('Ymdhis') . '_' . $name;
	$migration = <<<MODEL
<?php
/**
 * Use the up method to describe the SQL that will be used to create/alter tables, columns.
 *
 * Use the down method to undo what the up method has described.
 */
/**
 * ClassBlock
 */
class Migration_$name extends Migration{
	
	public function up(){
		
	}
	
	
	public function down(){
		
	}
	
	
}
MODEL;
	write_file($migration, PROJECT_ROOT . 'db/migrations/' . $name . '.migration.php');
}

function generate_controller($name, $argv){
	$namespace = PR_APPLICATION_NAMESPACE;
	$methods = '';
	foreach($argv as $value){
		$methods .= <<<METHOD
	/**
	 * MethodBlock
	 */
	public function $value(){
		
	}
	

METHOD;
	}

	$arr = explode('/', $name);
	//var_dump($arr);
	$helperName = $controllerName = array_pop($arr);
	$controllerName = $controllerName  . "Controller";
	$helperName = $helperName . "Helper";
	$namespace_path = $namespace . '\App\Controllers';
	$use = '';
	$extend_namespace = 'ApplicationController';
	$path = '';
	if(sizeof($arr) > 0){
		$use = <<<USE
		
/**
 * Set up the use for the main controllers
 */
use $namespace_path;
USE;
		$extend_namespace = 'Controllers\ApplicationController';
		foreach($arr as $namespace_token){
			$namespace_path .= "\\" . $namespace_token;
			$path .= $namespace_token . '/';
			//print $namespace_token . '<br/>';
		}
	}
	//die($path);
	$namespace = 'namespace ' . $namespace_path . ';';
	
	$controller = <<<CLASS
<?php
/**
 * PageBlock
 */
/**
 * Namespace for the controllers
 */
$namespace
$use

/**
 * ClassBlock
 */
class $controllerName extends $extend_namespace{
		
$methods
}
CLASS;
	

    $helper = <<<FILE
<?php

FILE;
	write_file($controller, PROJECT_ROOT . 'app/controllers/' . strtolower($path) . $controllerName . ".php");
	write_file($helper, PROJECT_ROOT . 'app/helpers/' . strtolower($path) . $helperName . '.php');
	generate_views($name, $argv);
}

function generate_views($controller_name, $argv)
{
	$Controller = $controller_name . "Controller";
	$controller_name = preg_replace('/([^\s])([A-Z])/', '\1-\2', $controller_name);
	$file_name = preg_replace('%\-%', '', $controller_name);

	$path = PROJECT_ROOT . 'app/views/' . strtolower($file_name);
	$c_name = preg_replace('%\/%', '\\', $Controller);
	foreach($argv as $value){
		$file = <<<FILE
This file is generated for $c_name#$value.
FILE;
		write_file($file, $path . '/' . $value . '.html.php');
	}
}

function write_file($content, $path){
	$boolean = false;
	//Create the folders
	$folders = explode('/', $path);
	
	//Take off the file.
	array_pop($folders);
	$folder_path = '';
	foreach($folders as $folder){
		$folder_path .= $folder . '/';
		if(!is_dir($folder_path)){
			mkdir($folder_path);
			//exit();
		}
	}
	
	//Write the file
	if(!is_dir($path) && !is_file($path)){
		$fp = fopen($path, 'w');
		$boolean = fwrite($fp, $content);
	}
	if($boolean === false){
		print "Skipped: $path\n";
	}else{
		print "Created: $path\n";
	}
}