#!/usr/bin/php -q
<?php

$script = array_shift($argv);
$operation = array_shift($argv);

if(is_file('script/rake/' . $operation)){
	print "\n./rake routes ouput:\n\n";
	include 'script/rake/' . $operation;
}else{
	print "\nThere is no RAKE task: $operation\n\n";
}